/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface Category { 
    categoryId?: number;
    categoryName?: string | null;
    description?: string | null;
    picture?: string | null;
    products?: Array<Product> | null;
}

