/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';


export interface CustomerDemographic { 
    customerTypeId?: string | null;
    customerDesc?: string | null;
    customers?: Array<Customer> | null;
}

