/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Territory } from './territory';
import { SellingOrder } from './sellingOrder';


export interface Employee { 
    employeeId?: number;
    lastName?: string | null;
    firstName?: string | null;
    title?: string | null;
    titleOfCourtesy?: string | null;
    birthDate?: string | null;
    hireDate?: string | null;
    address?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
    homePhone?: string | null;
    extension?: string | null;
    photo?: string | null;
    notes?: string | null;
    reportsTo?: number | null;
    photoPath?: string | null;
    inverseReportsToNavigation?: Array<Employee> | null;
    orders?: Array<Order> | null;
    reportsToNavigation?: Employee;
    sellingOrders?: Array<SellingOrder> | null;
    territories?: Array<Territory> | null;
}

