/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Product } from './product';


export interface OrderDetail { 
    orderId?: number;
    productId?: number;
    unitPrice?: number;
    quantity?: number;
    discount?: number;
    order?: Order;
    product?: Product;
}

