/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetail } from './orderDetail';
import { Employee } from './employee';
import { Customer } from './customer';
import { Shipper } from './shipper';


export interface Order { 
    orderId?: number;
    customerId?: string | null;
    employeeId?: number | null;
    orderDate?: string | null;
    requiredDate?: string | null;
    shippedDate?: string | null;
    shipVia?: number | null;
    freight?: number | null;
    shipName?: string | null;
    shipAddress?: string | null;
    shipCity?: string | null;
    shipRegion?: string | null;
    shipPostalCode?: string | null;
    shipCountry?: string | null;
    customer?: Customer;
    employee?: Employee;
    orderDetails?: Array<OrderDetail> | null;
    shipViaNavigation?: Shipper;
}

