/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetail } from './orderDetail';
import { Category } from './category';
import { SellingOrder } from './sellingOrder';
import { Supplier } from './supplier';


export interface Product { 
    productId?: number;
    productName?: string | null;
    supplierId?: number | null;
    categoryId?: number | null;
    quantityPerUnit?: string | null;
    unitPrice?: number | null;
    unitsInStock?: number | null;
    unitsOnOrder?: number | null;
    reorderLevel?: number | null;
    discontinued?: boolean;
    category?: Category;
    orderDetails?: Array<OrderDetail> | null;
    sellingOrders?: Array<SellingOrder> | null;
    supplier?: Supplier;
}

