/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Territory } from './territory';


export interface Region { 
    regionId?: number;
    regionDescription?: string | null;
    territories?: Array<Territory> | null;
}

