/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellingOrderUpdateDto { 
    idSellingOrder?: number;
    idEmployee?: number;
    idProduct?: number;
    quantity?: number;
}

