/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { Product } from './product';


export interface SellingOrder { 
    idSellingOrder?: number;
    idEmployee?: number;
    idProduct?: number;
    quantity?: number;
    idEmployeeNavigation?: Employee;
    idProductsNavigation?: Product;
}

