/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface Shipper { 
    shipperId?: number;
    companyName?: string | null;
    phone?: string | null;
    orders?: Array<Order> | null;
}

