/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface Supplier { 
    supplierId?: number;
    companyName?: string | null;
    contactName?: string | null;
    contactTitle?: string | null;
    address?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
    fax?: string | null;
    homePage?: string | null;
    products?: Array<Product> | null;
}

