/**
 * ProductsService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { Region } from './region';


export interface Territory { 
    territoryId?: string | null;
    territoryDescription?: string | null;
    regionId?: number;
    region?: Region;
    employees?: Array<Employee> | null;
}

